name: Unsafe Reviewers Check Clone
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened, synchronize]

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  UnsafeReview:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged != true && github.event.action != 'closed'
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v4
        with:
          path: base
          fetch-depth: 0
      - name: Checkout head repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          path: head-repo

      - name: Run unsafe code review script
        run: ls $GITHUB_WORKSPACE/base && pip3 install -r $GITHUB_WORKSPACE/base/scripts/add_unsafe_reviewers/requirements.txt && python3 $GITHUB_WORKSPACE/base/scripts/add_unsafe_reviewers/add-unsafe-reviewers.py $GITHUB_WORKSPACE/head-repo "origin/${{ github.base_ref }}" --token "${{ secrets.GITHUB_TOKEN }}" --pull-request "${{ github.event.number }}"
        shell: bash
